[build]
  base = "FrontEnd/book-store-app"
  publish = "FrontEnd/book-store-app/dist"
  command = "npm ci && npm run build"

[context.production.environment]
  VITE_API_BASE = "https://your-backend.example.com"
